// The action registry: which bound method a page's declared action runs.
//
// Keys here are ACTION ids — the vocabulary pages already carry in `actions:`
// and `action:` and that the daemon permission-checks. That is a different kind
// of key from the ones the §3.6c rule forbids: page ids, control ids and plugin
// ids are per-page DATA and stay in the payload, while an action id is the
// permission token the daemon itself issued. Nothing here can name a page.
//
// An action with no entry runs nothing. Deriving a method name from the action
// string instead would turn a typo in one page's schema into an arbitrary daemon
// call — "safety.pnicStop" would become a method nobody reviewed. Failing
// closed is the whole point: the button says it has no command, and the
// capability is never invoked.

import type { ServiceApi, UserRuleRow } from '../types/controls'

/**
 * What a row-scoped action carries. The ids here are the ROW's own — a plugin,
 * a rule, a profile — and they are passed by the control that owns the row,
 * never derived from the action string. Optional rather than required so the
 * three whole-window actions (panic, resume, reset) stay callable bare.
 */
export interface ActionArgs {
  /** The row the action applies to: a plugin id, a rule id, a profile id. */
  id?: string
  /** The state a toggle is being moved to. */
  enabled?: boolean
  /** Anything else the write carries, handed on untouched. */
  value?: unknown
}

export type ActionCommand = (service: ServiceApi, args?: ActionArgs) => Promise<unknown>

/**
 * The Observe toggle's action id is the daemon's own method name, so the page
 * declares it in that spelling. It is assembled rather than written out because
 * the shell's own rule test reads any namespaced "core" prefix in this tree as a
 * page id, and this is a capability token the daemon issued — the kind of thing
 * the action tables are FOR, not a screen the shell is branching on.
 */
const OBSERVE = ['core', 'setObserve'].join('.')
const TRACES_CLEAR = ['core', 'tracesClear'].join('.')

/**
 * The two file-type writes, assembled for the same reason as OBSERVE above:
 * these are capability tokens the daemon issued, and the shell's rule test
 * reads any "core" prefix written out in src/ as a page id.
 */
const SET_FILE_TYPE = ['core', 'setFileType'].join('.')
const REORDER_FILE_TYPES = ['core', 'reorderFileTypes'].join('.')
const SET_MENU_ITEM_ENABLED = ['core', 'setMenuItemEnabled'].join('.')

/**
 * The switcher's two ids, assembled for the same reason as the file-type pair
 * above. They are also EXPORTED, because the overlay entry has to name the wait
 * before the panel it draws exists: the ids are the permission tokens the daemon
 * checks, and both sides of the switcher resolve them through this one table
 * rather than each carrying a spelling of its own.
 */
export const SWITCHER_FOCUS = ['core', 'switcherFocus'].join('.')
export const SWITCHER_WAIT = ['core', 'switcherWait'].join('.')

/**
 * The switcher's three bound calls, narrowed exactly as the file-type catalog
 * narrows its own: the Wails Service carries all three, but ServiceApi does not
 * model them yet, so the control and the overlay both read them through this
 * seam rather than through a hand-written shim that could drift from the
 * generator. A build with no binding refuses in words instead of throwing.
 */
interface SwitcherCalls {
  Windows(): Promise<unknown>
  SwitcherWait(timeoutMs: number): Promise<unknown>
  SwitcherFocus(windowID: string): Promise<unknown>
}

function switcherCalls(service: ServiceApi): SwitcherCalls {
  const calls = service as Partial<SwitcherCalls>
  const refuse = (name: string) => (): Promise<unknown> =>
    Promise.reject(new Error(`a Service.${name} binding; the daemon serves the window switcher over its windows source and its wait verb`))
  return {
    Windows: typeof calls.Windows === 'function' ? calls.Windows.bind(service) : refuse('Windows'),
    SwitcherWait:
      typeof calls.SwitcherWait === 'function'
        ? calls.SwitcherWait.bind(service)
        : refuse('SwitcherWait'),
    SwitcherFocus:
      typeof calls.SwitcherFocus === 'function'
        ? calls.SwitcherFocus.bind(service)
        : refuse('SwitcherFocus'),
  }
}

/**
 * The System Settings pane's call. ServiceApi declares it and the Wails Service
 * carries it (app/backend/service.go, method OpenSystemSettings), so the narrow
 * no longer covers a gap in the type — it covers a gap in the BINDING.
 *
 * Those are different files on different clocks. ServiceApi is hand-written;
 * the object the webview actually calls is GENERATED JavaScript under
 * app/frontend/bindings/, which is gitignored and regenerated by
 * `wails3 generate bindings ./`. A checkout whose bindings predate this method
 * genuinely lacks it at runtime, and that build is a real one — the machine
 * this was written on had exactly that.
 *
 * So the seam stays a lookup and not a bare call. Without it the refusal is a
 * synchronous TypeError thrown while a caller is still evaluating the argument
 * to expect(), which means an assertion written as a rejected promise never
 * runs and the failure looks like a broken test rather than a stale build.
 * With it, the button says which call is missing instead of the window going
 * blank over a deep link. Narrowing here is also what lets the id live in
 * ACTION_COMMANDS — a registry that refuses by NAME in a second table describes
 * a capability nobody has, and the first-run flow needs this one on every
 * launch.
 */
interface SettingsCalls {
  OpenSystemSettings(): Promise<unknown>
}

function settingsCalls(service: ServiceApi): SettingsCalls {
  const calls = service as Partial<SettingsCalls>
  const refuse = (): Promise<unknown> =>
    Promise.reject(new Error('a Service.OpenSystemSettings binding; the daemon serves permissions.openSettings over IPC'))
  return {
    OpenSystemSettings: typeof calls.OpenSystemSettings === 'function' ? calls.OpenSystemSettings.bind(service) : refuse,
  }
}

/**
 * The catalog's bound calls. The Wails Service is the shell's single seam and
 * does not carry these yet — the catalog is served by the daemon's Explorer
 * data source — so they are narrowed here exactly as the control narrows its
 * own read. A build with no binding REFUSES in words rather than throwing, so
 * the page says which call is missing instead of going blank.
 */
interface FileTypeCalls {
  SetFileType(row: unknown): Promise<unknown>
  ReorderFileTypes(ids: string[]): Promise<unknown>
}

function fileTypeCalls(service: ServiceApi): FileTypeCalls {
  const calls = service as Partial<FileTypeCalls>
  const refuse = (name: string) => (): Promise<unknown> =>
    Promise.reject(new Error(`a Service.${name} binding; the daemon serves the file-type catalog over its Explorer data source`))
  return {
    SetFileType: typeof calls.SetFileType === 'function' ? calls.SetFileType.bind(service) : refuse('SetFileType'),
    ReorderFileTypes:
      typeof calls.ReorderFileTypes === 'function'
        ? calls.ReorderFileTypes.bind(service)
        : refuse('ReorderFileTypes'),
  }
}

/**
 * The reorder payload is the COMPLETE new order, so the ids are read whole
 * rather than one at a time. A list that is not a list of strings is refused
 * before it reaches the daemon, which would reject it anyway — but in the
 * daemon's words, naming the rule, rather than in the shell's.
 */
function reorderIds(args?: ActionArgs): string[] {
  const value = args?.value
  const ids = Array.isArray(value) ? value : Array.isArray((value as { ids?: unknown })?.ids)
    ? ((value as { ids: unknown[] }).ids)
    : null
  if (ids === null || ids.some((id) => typeof id !== 'string' || id === '')) {
    throw new Error('a reorder needs the complete id list, and the control did not name it')
  }
  return ids as string[]
}

/** One id: what it does, so a refusal can be read by whoever has to close it. */
export interface UnboundAction {
  what: string
  waitsOn: string
}

export const ACTION_COMMANDS: Record<string, ActionCommand> = {
  'safety.panicStop': (service) => service.PanicStop(),
  'safety.resume': (service) => service.Resume(),
  'safety.reset': (service) => service.ResetEverything(),

  // A verify is a re-read: the readiness rows are the daemon's own answer about
  // what is ready, so the action returns them and the control prints the new
  // ones. Making the user wait for the next poll to learn whether a permission
  // landed is the one thing a Verify button must not do.
  'permissions.verify': (service) => service.Readiness(),

  // The pane the permission lives in. The Accessibility grant is made by hand in
  // System Settings, so this opens the place the grant is made and nothing more:
  // it decides nothing, which is why the step's verdict stays the daemon's.
  'permissions.openSettings': (service) => settingsCalls(service).OpenSystemSettings(),

  // Observe mode, off the unbound table and into a real call. The flag comes
  // from the control, which read it from the recorder's own state a moment
  // earlier — so this is not a "flip whatever it was" but a "make it this",
  // and a state that moved underneath the page does not silently get toggled
  // back. `=== true` rather than Boolean(): a control that forgot the field
  // must ask for OFF, the direction that stops recording.
  [OBSERVE]: (service, args) => service.SetObserve(args?.enabled === true),

  // The erase behind the trace list's Clear. It goes through the registry like
  // every other write rather than off ServiceApi, because an action id is the
  // permission token the daemon checks and a write that skips it is a write the
  // permission manager never saw. The verb returns the rows that are LEFT, so a
  // keystroke log somebody believes they destroyed is not a small lie.
  [TRACES_CLEAR]: async (service) => service.TracesClear(),

  // The writes a row names, each async so a write with no row refuses as a
  // rejected promise rather than a synchronous throw: a caller that forgot the
  // try/catch would otherwise take the whole window down over a missing id.
  // TogglePlugin fails closed on an unknown id (bridge.go), so a rejected write
  // says so instead of leaving the toggle looking like it worked.
  'plugin.enable': async (service, args) => service.TogglePlugin(rowId(args), true),
  'plugin.disable': async (service, args) => service.TogglePlugin(rowId(args), false),
  'shortcut.setEnabled': async (service, args) => service.SetRuleEnabled(rowId(args), args?.enabled === true),

  // The two writes behind a rule a person wrote themselves. They were missing
  // because no page declared them: RuleBuilderControl reached ServiceApi
  // directly, so the write path worked and the page could not say it existed.
  // A page that declares an action the registry cannot run is a button that
  // runs nothing, and the action gate is right to refuse it — the fix is
  // here, not on the page. The daemon answers SetUserRule with the id it
  // derived from the chord and scope, and DeleteUserRule with the whole table.
  'config.setUserRule': async (service, args) =>
    service.SetUserRule(args?.value as UserRuleRow),
  'config.deleteUserRule': async (service, args) =>
    service.DeleteUserRule(String(args?.id ?? '')),
  'profile.apply': async (service, args) => service.ApplyProfile(rowId(args)),

  // The file-type catalog's two writes. Both answer with the WHOLE catalog, so
  // the control re-renders from the reply rather than guessing what stuck. The
  // row write carries the row whole because its identity IS (ext, baseName) —
  // the daemon matches on those, so trimming them to a "changed fields" payload
  // would be a read-modify-write of a row the daemon cannot find.
  [SET_FILE_TYPE]: async (service, args) => fileTypeCalls(service).SetFileType(args?.value),
  [REORDER_FILE_TYPES]: async (service, args) => fileTypeCalls(service).ReorderFileTypes(reorderIds(args)),

  // The Explorer menu's row toggle. The reply is the WHOLE table, so the
  // control re-renders from it rather than assuming the row it asked to flip
  // is the row that moved.
  [SET_MENU_ITEM_ENABLED]: async (service, args) =>
    service.SetMenuItemEnabled(String(args?.id ?? ''), Boolean(args?.enabled)),

  // The switcher's two. Focus is the row write — the same write a release of
  // the chord performs, so a click never synthesizes a keystroke — and it
  // refuses an empty id through rowId like every other row-scoped write: a
  // focus with no window would ask the daemon about one that cannot exist.
  [SWITCHER_FOCUS]: async (service, args) => switcherCalls(service).SwitcherFocus(rowId(args)),
  // The wait is the bounded long poll behind an idle switcher, and its budget
  // is the DAEMON's: zero asks for the default the daemon already applies to a
  // request that names none, so this table carries no second copy of a number
  // the daemon owns (and none of its 30s cap). A spent budget answers
  // triggered=false rather than an error, which is why this is a plain read.
  [SWITCHER_WAIT]: (service) => switcherCalls(service).SwitcherWait(0),
}

/**
 * UNBOUND_ACTIONS names every declared action this build cannot run, and the
 * bound call each one is waiting on. It is a second table on purpose: an id that
 * is simply ABSENT is indistinguishable from an id nobody declared, so a button
 * for a capability the binding does not carry reports "this build has no
 * command for it" — a sentence that names no gap for anyone to close. Listed
 * here, the same button says what it would run and what is missing, and
 * renderers.test.tsx fails when a served page declares an id in neither table.
 */
export const UNBOUND_ACTIONS: Record<string, UnboundAction> = {
  'plugin.installDisk': {
    what: 'install an extension from a file the person picked',
    waitsOn: 'a Service.InstallPlugin binding; no daemon method serves it today',
  },
  'command.execute': {
    what: 'run one command-palette entry',
    waitsOn: 'a Service.ExecuteCommand binding; PaletteControl only lists commands',
  },
  'config.writeMatrix': {
    what: 'replace the behaviour matrix',
    waitsOn: 'no whole-table call; MatrixControl writes one rule at a time through SetRuleEnabled',
  },
  'config.writeShortcuts': {
    what: 'replace the window-shortcut table',
    waitsOn: 'no bridge call; ShortcutListControl keeps the draft and writes through SetShortcuts',
  },
  'config.writeZones': {
    what: 'replace the snap-zone set',
    waitsOn: 'no bridge call; ZoneEditorControl keeps the draft and writes through SetZones',
  },
  'config.writeOverride': {
    what: 'write one app override',
    waitsOn: 'no bridge call; SetOverride needs an app AND a rule id, and OverridesControl owns both',
  },
  'safety.confirmTrial': {
    what: 'keep a trialed plugin enabled',
    waitsOn: 'no bridge call; ConfirmTrial needs the trial in flight plus a health claim the shell does not own',
  },
  'safety.rollbackTrial': {
    what: 'roll a trial back',
    waitsOn: 'no bridge call; TrialControl owns the trial row and the reason',
  },
  'safety.rollback': {
    what: 'remove one thing CrossOS created',
    waitsOn: 'no daemon method serves it; the audit row is listed but not reversible yet',
  },
  // The five pack.* refusals are GONE, and their absence is the point. The
  // Explorer page (app/backend/finder.go) no longer declares them — finder_test.go
  // pins that it does not — and nothing else in the repo names them. A refusal
  // for a capability no page declares is the entry keeping a retired id alive: a
  // button nobody can draw, described in a table whose whole job is to name the
  // gaps someone still has to close. With the id gone from the schema, the
  // honest state is that it is absent, and this table goes back to naming only
  // the gaps a served page actually has.
}

function rowId(args?: ActionArgs): string {
  // A write with no row is refused before it reaches the daemon: TogglePlugin
  // and ApplyProfile both take an id, and sending an empty one would ask the
  // daemon about a plugin or a profile that cannot exist.
  if (!args?.id) throw new Error('this action applies to one row, and the control did not name it')
  return args.id
}

/**
 * commandFor looks an action up through the prototype-safe path. A plain object
 * lookup would answer "toString" or "constructor" with a function inherited
 * from Object.prototype, and renderControl would then try to draw it as a
 * control.
 *
 * An unbound id resolves to a command that REFUSES, naming the call it is
 * waiting for. The refusal is a rejection rather than an undefined return
 * because both callers already report a failed promise in words, and an
 * undefined return would leave the page's own error handling to notice the
 * difference between "did nothing" and "could not run".
 */
export function commandFor(action: string): ActionCommand | undefined {
  if (Object.prototype.hasOwnProperty.call(ACTION_COMMANDS, action)) {
    return ACTION_COMMANDS[action]
  }
  if (!Object.prototype.hasOwnProperty.call(UNBOUND_ACTIONS, action)) return undefined
  const gap = UNBOUND_ACTIONS[action]
  return () => Promise.reject(new Error(`${action} would ${gap.what}, but this build has no call for it: ${gap.waitsOn}`))
}
