#!/usr/bin/env bash
# Render every page the daemon serves and write the PNGs into docs/screenshots/.
#
# These are committed on purpose, and it is worth saying why that reverses what
# docs/baseline/README.md says about the React screenshots: those were kept out
# because nothing regenerated them, so they went stale the moment anything
# changed and quietly stopped being evidence. A picture nobody can get a fresh
# copy of is not a check, it is a rumour.
#
# This one is regenerated by this script and committed alongside the change that
# produced it, so "what does it look like now" has an answer you can open.
#
# The window needs a running daemon. `./scripts/run.sh --no-open` starts one.
#
#   ./scripts/screenshots.sh              # into docs/screenshots/
#   ./scripts/screenshots.sh /tmp/out     # somewhere else, committed nowhere
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

OUT="${1:-docs/screenshots}"
BIN="macos/.build/debug/CrossOS"

if [[ ! -x "$BIN" ]]; then
  echo "==> Building the shell"
  swift build --package-path macos >/dev/null
fi

if [[ ! -S "$HOME/Library/Application Support/CrossOS/crossos.sock" ]]; then
  echo "==> No daemon on the socket — start one with: ./scripts/run.sh --no-open" >&2
  exit 1
fi

echo "==> Rendering every page into $OUT"
# --window, not the bare --shots: a picture of the content pane alone is half
# the app. Every layout defect this repo fixed for a while was measured on that
# half, and the navigation rail was broken the entire time.
"$BIN" --shots --window --out="$OUT"

# Dark as well as light. Every screenshot in this repo's history was taken in
# the light appearance, because `--dark` was never passed: the flag is `--dark`,
# not `--appearance=dark`, and nothing in the docs said so. The dark palette is
# not a variant of the light one that has been seen — it is a palette nobody had
# looked at, on an app that is meant to follow the user's Appearance setting.
# The surface check is what caught it: `--dark` renders a rail at (55,55,55)
# against a (30,30,30) pane, while the light run's "dark" screenshots were in
# fact (255,255,255) and light.
DARK_OUT="$OUT-dark"
echo "==> Rendering every page again in the DARK appearance"
"$BIN" --dark --shots --window --out="$DARK_OUT"

echo "==> Measuring the rendered pages"
# The images are the only artefact in this repo that is not a claim about the
# app. So the script that makes them also checks them, and fails here rather
# than leaving a bad picture to be committed and believed.
python3 scripts/analyze-shot.py "$OUT"/*.png
python3 scripts/check-rhythm.py "$OUT"/*.png
# Dark too. `analyze-shot.py` samples its background from the corners, so it
# works in either appearance; the rhythm check reads the same sidecars.
python3 scripts/analyze-shot.py "$DARK_OUT"/*.png >/dev/null
python3 scripts/check-rhythm.py "$DARK_OUT"/*.png | grep -E "FAIL" || true

echo "==> Done. $(find "$OUT" -maxdepth 1 -name '*.png' | wc -l | tr -d ' ') screenshots in $OUT"